"""
This is an explanation for Inmoov joints
## =_= ##
God Damn, this is so tedious, copyright @ TeTe @SJTU
"""

joint_registry = {
    2: "waist_rotation",
    4: "waist_lean",
    7: "head_tilt",
    8: "head_updown",
    9: "head_leftright",
    10: "jaw",
    13: "eyes_updown",
    14: "right_eye_leftright",
    18: "left_eye_leftright",
    24: "right_shoulder_up",
    25: "right_bicep_rotate",
    26: "right_shoulder_side",
    27: "right_bicep",
    28: "right_hand",
    29: "right_thumb1",
    30: "right_thumb",
    31: "right_thumb3",
    33: "right_index1",
    34: "right_index",
    35: "right_index3",
    37: "right_middle1",
    38: "right_middle",
    39: "right_middle3",
    41: "right_ring1",
    42: "right_ring",
    43: "right_ring3",
    44: "right_ring4",
    47: "right_pinky1",
    48: "right_pinky",
    49: "right_pinky3",
    50: "right_pinky4",
    55: "left_shoulder_up",
    56: "left_bicep_rotate",
    57: "left_shoulder_side",
    58: "left_bicep",
    59: "left_hand",
    # 60: "left_thumb1",
    # 61: "left_thumb",
    # 62: "left_thumb3",
    # 64: "left_index1",
    # 65: "left_index",
    # 66: "left_index3",
    # 68: "left_middle1",
    # 69: "left_middle",
    # 70: "left_middle3",
    # 72: "left_ring1",
    # 73: "left_ring",
    # 74: "left_ring3",
    # 75: "left_ring4",
    # 78: "left_pinky1",
    # 79: "left_pinky",
    # 80: "left_pinky3",
    # 81: "left_pinky4",
}


control_joint = {
    24: "right_shoulder_up",
    25: "right_bicep_rotate",
    26: "right_shoulder_side",
    27: "right_bicep",
    28: "right_hand",
    29: "right_thumb1",
    30: "right_thumb",
    31: "right_thumb3",
    33: "right_index1",
    34: "right_index",
    35: "right_index3",
    37: "right_middle1",
    38: "right_middle",
    39: "right_middle3",
    41: "right_ring1",
    42: "right_ring",
    43: "right_ring3",
    44: "right_ring4",
    47: "right_pinky1",
    48: "right_pinky",
    49: "right_pinky3",
    50: "right_pinky4",
    # 55: "left_shoulder_up",
    # 56: "left_bicep_rotate",
    # 57: "left_shoulder_side",
    # 58: "left_bicep",
    # 59: "left_hand"
}